WITH RECURSIVE TREE AS (
  SELECT ID, PARENT, TITLE
  FROM ETU_ELEMENT
  WHERE PARENT IS NULL
  UNION ALL
  SELECT E.ID, E.PARENT, E.TITLE
  FROM ETU_ELEMENT E
  JOIN TREE AS T ON E.PARENT=T.ID
)
SELECT * FROM TREE
